### ISSUE TITLE
TB Quadrupole Model01 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/tb-quadrupoles#1]
tb-quadrupoles/model-01/simulation/2017-01-09_TB_Quadrupole_Model01_Sim_X=-20_20mm_Z=-450_450mm_Imc=10A.txt

**Comment by xresende** [comment]
* integrated quadrupole from fieldmap at maximum current 10A reached spec of > 8 T/m.
* higher order multipoles are all small

model APPROVED.
